Areas/Admin/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EPSN;

namespace EPSN.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ArticlesController : Controller
    {
        private CoursesDBEntities db = new CoursesDBEntities();

        // GET: Admin/Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Writer);
            return View(articles.ToList());
        }

        // GET: Admin/Articles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Admin/Articles/Create
        public ActionResult Create()
        {
            ViewBag.Writer_ID = new SelectList(db.Writers, "ID_Writer", "Name_Writer");
            return View();
        }

        // POST: Admin/Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                article.Image_Article = upload.FileName;
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Writer_ID = new SelectList(db.Writers, "ID_Writer", "Name_Writer", article.Writer_ID);
            return View(article);
        }

        // GET: Admin/Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.Writer_ID = new SelectList(db.Writers, "ID_Writer", "Name_Writer", article.Writer_ID);
            return View(article);
        }

        // POST: Admin/Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article article, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                article.Image_Article = upload.FileName;
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Writer_ID = new SelectList(db.Writers, "ID_Writer", "Name_Writer", article.Writer_ID);
            return View(article);
        }

        // GET: Admin/Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Admin/Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ArticlesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace EPSN.Controllers
{
    public class ArticlesController : Controller
    {
        private CoursesDBEntities db = new CoursesDBEntities();
        // GET: Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Writer);
            return View(articles.ToList());
        }
        public ActionResult Content(int? Id)
        {
            var articleContents = db.Articles.Find(Id);
            if (Id == null || Id == 0)
            {
                return HttpNotFound();
            }
            return View(articleContents);
        }
        public ActionResult Category(int? id)
        {
            var Category_Articles = db.Categories_Articles.Where(a => a.Article_ID == id && a.Category_ID == id).ToList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(Category_Articles);
        }
        public ActionResult Writer(int? id)
        {
            var writer = db.Articles.Where(a => a.Writer_ID == id).ToList();
            return View(writer);
        }
    }
}

Areas/Admin/Views/Articles/Create.cshtml
@model EPSN.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Create", "Articles", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_Article, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discription_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Discription_Article, new { htmlAttributes = new { @class = "form-control" }, @id = "Discription_Article" })
                @Html.ValidationMessageFor(model => model.Discription_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="upload" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate_Article, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer_ID, "Writer_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Writer_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Writer_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discript, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discript, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discript, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    CKEDITOR.replace("Discription_Article");
</script>

Areas/Admin/Views/Articles/Delete.cshtml
@model EPSN.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_Article)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Article)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discription_Article)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.Discription_Article).ToString()))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_Article)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Image_Article)" class="thumbnail" style="width:100px; height:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate_Article)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate_Article)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discript)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writer.Name_Writer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writer.Name_Writer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Admin/Views/Articles/Details.cshtml
@model EPSN.Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_Article)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_Article)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discription_Article)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.Discription_Article).ToString()))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_Article)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Image_Article)" class="thumbnail" style="width:100px; height:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate_Article)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate_Article)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discript)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discript)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writer.Name_Writer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writer.Name_Writer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Article }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/Articles/Edit.cshtml
@model EPSN.Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Edit", "Articles", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Article)

        <div class="form-group">
            @Html.LabelFor(model => model.Name_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_Article, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discription_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Discription_Article, new { htmlAttributes = new { @class = "form-control" }, @id = "Discription_Article" })
                @Html.ValidationMessageFor(model => model.Discription_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="upload" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate_Article, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate_Article, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate_Article, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer_ID, "Writer_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Writer_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Writer_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discript, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discript, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discript, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    CKEDITOR.replace("Discription_Article");
</script>

Areas/Admin/Views/Articles/Index.cshtml
@model IEnumerable<EPSN.Article>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_Article)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription_Article)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image_Article)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationDate_Article)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discript)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Writer.Name_Writer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_Article)
        </td>
        <td>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => item.Discription_Article).ToString()))
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(model => item.Image_Article)" class="thumbnail" style="width:100px; height:100px;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate_Article)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discript)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Writer.Name_Writer)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_Article }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_Article }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_Article })
        </td>
    </tr>
}

</table>