Areas/Admin/Controllers/Category_ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EPSN;

namespace EPSN.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class Category_ArticleController : Controller
    {
        private CoursesDBEntities db = new CoursesDBEntities();

        // GET: Admin/Category_Article
        public ActionResult Index()
        {
            return View(db.Category_Article.ToList());
        }

        // GET: Admin/Category_Article/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Article category_Article = db.Category_Article.Find(id);
            if (category_Article == null)
            {
                return HttpNotFound();
            }
            return View(category_Article);
        }

        // GET: Admin/Category_Article/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category_Article/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category_Article category_Article, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                category_Article.Image_ID= upload.FileName;
                db.Category_Article.Add(category_Article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category_Article);
        }

        // GET: Admin/Category_Article/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Article category_Article = db.Category_Article.Find(id);
            if (category_Article == null)
            {
                return HttpNotFound();
            }
            return View(category_Article);
        }

        // POST: Admin/Category_Article/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category_Article category_Article, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                category_Article.Image_ID = upload.FileName;
                db.Entry(category_Article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category_Article);
        }

        // GET: Admin/Category_Article/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Article category_Article = db.Category_Article.Find(id);
            if (category_Article == null)
            {
                return HttpNotFound();
            }
            return View(category_Article);
        }

        // POST: Admin/Category_Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category_Article category_Article = db.Category_Article.Find(id);
            db.Category_Article.Remove(category_Article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Category_Article/Create.cshtml
@model EPSN.Category_Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Category_Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category_Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name_ArticleCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_ArticleCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_ArticleCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.Image_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Admin/Views/Category_Article/Delete.cshtml
@model EPSN.Category_Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category_Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_ArticleCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_ArticleCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_ID)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Image_ID)" class="thumbnail" style="width:100px; height:100px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Admin/Views/Category_Article/Details.cshtml
@model EPSN.Category_Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category_Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_ArticleCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_ArticleCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_ID)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Image_ID)" class="thumbnail" style="width:100px; height:100px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_ArticleCategory }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/Category_Article/Edit.cshtml
@model EPSN.Category_Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Category_Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category_Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_ArticleCategory)

        <div class="form-group">
            @Html.LabelFor(model => model.Name_ArticleCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_ArticleCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_ArticleCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.Image_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Admin/Views/Category_Article/Index.cshtml
@model IEnumerable<EPSN.Category_Article>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_ArticleCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image_ID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_ArticleCategory)
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(model => item.Image_ID)" class="thumbnail" style="width:100px; height:100px;" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_ArticleCategory }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_ArticleCategory }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_ArticleCategory })
        </td>
    </tr>
}

</table>